name: Ping URL
description: A GitHub Action to ping a specified URL and check its availability until maximum retries are reached.

inputs:
  url:
    description: The URL to ping
    required: true
  max-retries:
    description: The maximum number of retries to ping the URL
    required: false
    default: 10
  delay-interval:
    description: The interval (in seconds) between retries
    required: false
    default: 5

runs:
  using: docker
  image: Dockerfile