name: 09 - Using Functions
on:
  pull_request:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 20 seconds
        run: sleep 20
      - name: Failing step
        run: exit 1
      - name: I will be skipped
        if: ${{ success() }}
        run: echo "This step will execute only if the previous step succeeds."
      - name: I will execute
        if: ${{ failure() }}
        run: echo "This step will execute if any previous step fails."
      - name: I will execute
        if: ${{ !cancelled() }}
        run: echo "This step will execute regardless of the previous steps' outcomes, except when the workflow run is cancelled."
      - name: I will execute when cancelled
        if: ${{ cancelled() }}
        run: echo "This step will execute only if the workflow run is cancelled."