name: 19 - 1 - Managing Concurrency
on:
  workflow_dispatch:

# This workflow demonstrates how to manage concurrency in GitHub Actions at workflow level.
# It ensures that only one instance of this workflow runs at a time for a given branch or tag.
# If another instance is triggered while one is already running, the new instance will be queued until the current one finishes.

# Concurrency group names in GitHub Actions are indeed case-insensitive, meaning that different capitalizations for the same name are treated as identical. This understanding is crucial for properly managing concurrency limits and ensuring that workflows queue correctly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.invalidurl.com
          max_retries: 20
          delay_interval: 5