name: 20 - Workflow Security
on:
  pull_request:

# Context: GitHub allows you to execute commands in its PR name, which can lead to security vulnerabilities if not handled properly.
# This workflow demonstrates how to safely access the PR title without risking command injection.
# In the "unsafe-pr" job, the PR title is accessed directly in the shell command, which can be exploited if the title contains malicious code.
# In contrast, the "safer-pr" job uses an environment variable to access the PR title, which prevents any potential command injection attacks.
# The "js-safer-pr" job demonstrates how to use a custom GitHub Action that safely checks the PR title using Node.js, further reducing the risk of command injection.

jobs:
  unsafe-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PR title
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ "$title" == ^feat ]]; then
            echo "PR is a feature"
            exit 0
          else
            echo "PR is not a feature. Failing the workflow."
            exit 1
          fi
  safer-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$TITLE" == ^feat ]]; then
            echo "PR is a feature"
            exit 0
          else
            echo "PR is not a feature. Failing the workflow."
            exit 1
          fi
  js-safer-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PR title
        uses: ./.github/actions/security-safe-input
        with:
          pr-title: ${{ github.event.pull_request.title }}